### ISSUE TITLE
OnlineStat interface not fully implemented

### ISSUE THREAD

**Issue by devmotion** [joshday/OnlineStats.jl#106]
Hi,

I tried to implement some custom statistics by following the instructions at https://github.com/joshday/OnlineStatsBase.jl. However, I noticed that not all statistics in OnlineStats fully implement the described interface. The following (stupid) code, e.g., fails since `_fit!` is not implemented for `Mean`:
```julia
import OnlineStatsBase: ExactStat, _fit!, _value

struct MyWrapper{S<:ExactStat{0}} <: ExactStat{0}
    stat::S
end
_fit!(o::MyWrapper, y::Real, w::Float64) = _fit!(o.stat, y, w)
_value(o::MyWrapper) = _value(o.stat)

using OnlineStats
y = randn(1000)
s = Series(MyWrapper(Mean()))
for yi in y
    fit!(s, yi)
end
```
```julia
ERROR: MethodError: no method matching _fit!(::OnlineStats.Mean, ::Float64, ::Float64)
```

Of course, this is a stupid example but one can easily think of more elaborate use cases such as `MV` which cause similar problems if one wants to rely only on methods `_fit!`, `_value`, and `merge!` that define the OnlineStats interface according to OnlineStatsBase. Especially if one wants to support custom OnlineStat statistics that are not defined in OnlineStats.jl, it seems weird to implement `_fit!` as
```julia
_fit!(o::MyWrapper, y::Real, w::Float64) = fit!(o.stat, y, w)
```
and hence to rely on the implementation of `fit!` which is not mentioned in the description of the OnlineStat interface. I would rather expect that all statistics in OnlineStats.jl fully implement the OnlineStat interface. Is there any reason why OnlineStats.jl currently does not fully support the interface?

**Comment by joshday** [comment]
There's a reason...although not a particularly good one.  

OnlineStatsBase was originally created so that JuliaDB could use OnlineStats without adding its dependencies (later on it was decided that the OnlineStats dependencies were worth picking up).  So I didn't have wrapper types in mind when I split off the essentials from OnlineStats.

I think the correct solution is to require StatsBase in OnlineStatsBase and avoid the hacky underscore methods.  I'll try to get to that this week.

**Comment by joshday** [comment]
There are new releases of OnlineStats/OnlineStatsBase that remove the underscore methods.  The interface is described a bit better now in the README of https://github.com/joshday/OnlineStatsBase.jl.
