### ISSUE TITLE
Weight that cannot be computed from nobs alone

### ISSUE THREAD

**Issue by jw3126** [joshday/OnlineStats.jl#131]
In some situations the weight of an observation cannot be computed from `nobs` alone:
### Example use cases
* I often analyze data coming from particle transport Monte Carlo simulations. Typical questions are how many  particles reach a certain region, or create a histogram of the energies of particles passing through some surface etc. Now these simulations make use of variance reduction techniques like splitting particles that are close to the region of interest etc. As a result, each particle has a statistical weight attached to it.
* Another use case would be taking a moving average with characteristic length 1day of the number of sold gadgets. An observation is just a time stamp of a single sold gadget.

It seems to me that this is currently not supported. Does this fit into the scope of `OnlineStats.jl`? If so, we can discuss an API then and I can provide a PR if you like.

**Comment by joshday** [comment]
The first example of using statistical weights is something I've thought about a little (https://github.com/joshday/OnlineStats.jl/issues/129).  One option would be to add three-argument methods for fit, `fit!(stat, observation<s>, weight<s>)`, where not all stats would have methods (since not everything uses weights e.g. `CountMap`).  

There is a moving window type (essentially just a circular buffer) I recently added, but it's not based on time like your example.

https://github.com/joshday/OnlineStats.jl/blob/40eeb23b9f5c94f197fad0b58756dc73f5c58be0/src/stats/stats.jl#L781-L791

A `MovingTimeWindow` type would be fairly straightforward to add, where a single observation was something like `Tuple{Dates.TimeType, T}`

**Comment by jw3126** [comment]
Ok I close this in favor of #129.
