### ISSUE TITLE
Odd Quantile results:

### ISSUE THREAD

**Issue by simonbyrne** [joshday/OnlineStats.jl#142]
```
using OnlineStats
X = rand(1000)
fit!(Quantile([0.001,0.005,0.01]),X)
```

gives
```
Quantile: n=1000 | value=[-0.748493, -1.10599, -0.829429]
```
1. All of the values in `X` are positive, and
2. the quantiles aren't even in the correct order!

Are there any special estimators you can use for extreme tail quantiles? it does seem like there should be more efficient things we could be doing (e.g. if you have 1000 values are are looking for the 0.01 quantile, you could just store the 10 smallest).

**Comment by joshday** [comment]
> Are there any special estimators you can use for extreme tail quantiles? it does seem like there should be more efficient things we could be doing (e.g. if you have 1000 values are are looking for the 0.01 quantile, you could just store the 10 smallest).

The problem with that approach is that as number-of-observations grows, so does the storage requirement.  In this example, for 10^6 observations you would need to store 10^4 values and that's just not scalable.  I've restricted the types in OnlineStats to use constant memory.  That's probably too strict a requirement for a lot of applications, but I like having that guarantee.  It is fairly easy to create your own types via OnlineStatsBase that do not have that restriction.

---

TODO: port this to docs

# `Quantile`
The algorithms that `Quantile` uses are meant for "truly big data" :

```julia
julia> x = rand(10^7);

julia> o = fit!(Quantile([.001,.005,.01]), x)
Quantile: n=10000000 | value=[0.00108976, 0.00506928, 0.0100592]

julia> quantile(x, [.001, .005, .01])
3-element Array{Float64,1}:
 0.001002449450815395
 0.00499638859513145
 0.009996964061886209
```

# Unfortunately, estimating quantiles online is much harder of a problem than it seems like it should be.  Other options are:

## `P2Quantile`

More accurate, but comes at the cost of slower updates.  Using same `X` as OP:

```julia
julia> fit!(P2Quantile(.001), X)
P2Quantile (0.001): n=1000 | value=0.00524199839367525

julia> quantile(X, .001)
0.0050606221152202
```
## Approximating quantiles from histograms

Again, more expensive to calculate, but allows you to calculate quantiles *after* running through the data.

#### `Hist(rng)`
Requires that you specify histogram bins before observing data
```julia
julia> o = fit!(Hist(0:.001:10), X)
Hist: n=1000 | value=(x = 0.0:0.001:10.0, y = [0, 1, 0, 0, 0, 2, 2, 3, 2, 4  …  0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

julia> quantile(o, .001)
0.005496000000000001
```

#### `KHist(k)` 
Think K-means clustering but for histograms (adaptively finds K approximately-equally-spaced bin centroids)

```julia
julia> o = fit!(KHist(50), X)
KHist: n=1000 | value=(x = [0.00149283, 0.00994069, 0.0250422, 0.0408243, 0.0610372, 0.07819, 0.0986384, 0.115158, 0.137917, 0.161102  …  0.817239, 0.841277, 0.863309, 0.890353, 0.914125, 0.929981, 0.948639, 0.971033, 0.992261, 0.998261], y = [1, 21, 6, 19, 12, 25, 23, 26, 26, 19  …  10, 23, 28, 28, 19, 27, 23, 22, 14, 1])

julia> quantile(o, .001)
0.009940693822873109
``` 

## `OrderStats(b)` 

Estimates the average order statistics for samples of size `b`.  Order statistics are biased, but this empirically works well (In this case, since you only observe 1000 values, the result is exact).

```julia
julia> o = fit!(OrderStats(1000), X)
OrderStats: n=1000 | value=[0.00149283, 0.00506419, 0.00555084, 0.00614886, 0.00620739, 0.00700921, 0.00745667, 0.00764043, 0.00831333, 0.00882082  …  0.99012, 0.992083, 0.994002, 0.994089, 0.994153, 0.994685, 0.995114, 0.995377, 0.997379, 0.998261]

julia> quantile(o, .001)
0.0050606221152202
```

**Comment by joshday** [comment]
Separate objects, but you can combine them in a `Series`: 

```julia
s = Series(P2Quantile.(.1:.1:.9)...)
```

> are there any tuneable options that say how many elements are used to approximate the quantile?

Not sure I understand the question, since each method does different things.  `Quantile` uses stochastic approximation: SGD, Adagrad, or my yet unpublished PhD research OMAS/MSPI (I can provide details if needed).  Here's the associated paper for `P2Quantile`: https://www.cse.wustl.edu/~jain/papers/ftp/psqr.pdf.

**Comment by simonbyrne** [comment]
By coincidence, this question came up on discourse:
https://discourse.julialang.org/t/package-for-approximate-small-quantiles/20046

**Comment by polytomous** [comment]
T-Digests give good (mostly) mergable streaming quantile estimates. https://github.com/tdunning/t-digest 
They're unique in that they offer really really really good error rates around the extremes of distributions. https://github.com/tdunning/t-digest/blob/master/docs/t-digest-paper/histo.pdf 

Implementation is straightforward enough, and there's a open source reference implementation you can benchmark against. I will probably end up adding t digets to vignette, my sketch data structure library, soon.

**Comment by evveric** [comment]
I find MSPI() algo can give better Quantile at "Extrema" cases
```

using OnlineStats
X = rand(1000)
fit!(Quantile([0.001,0.005,0.01];alg=MSPI()),X)
```

Can you try this?

`Quantile: n=1000 | value=[0.0060987, 0.0210089, 0.0415325]`

There must be some other drawback on this algo, that is why it is not the default one.
but it works for this particular case.

**Comment by polytomous** [comment]
@evveric what are the merging characteristics of MSPI tho? esp. as compared to other options? 

i stumbled on another option re: quantile estimates, something like moments merging method or whatever i forget the name / dont care to be transparent b/c it doesn't have the characteristics i like ;)

**Comment by joshday** [comment]
Since this issue was opened, I've changed `Quantile` to use `ExpandingHist` internally, which provides some big advantages:

1. Much more accurate for small n.
2. You can choose quantiles **after** fitting the data, e.g.

```Julia
julia> o = fit!(Quantile(), 1:10^6)
Quantile: n=1000000 | value=[1049.58, 2.50611e5, 5.00172e5, 7.49733e5, 9.99294e5]

julia> value(o)
5-element Vector{Float64}:
   1049.576
 250610.664
 500171.752
 749732.84
 999293.928

julia> value(o, 0.5)
500171.752

julia> value(o, [.1, .9])
2-element Vector{Float64}:
  99615.72
 900727.784
```
