### ISSUE TITLE
2D histograms

### ISSUE THREAD

**Issue by yakir12** [joshday/OnlineStats.jl#148]
This would be very powerful for processing coordinates, for instance:

```julia
xys = [[rand(2) for _ in 1:10] for _ in 1:3] # 3 tracks with 10 coordinates each
o = Hist(.2:0.1:.8, .3:.1:1) # dispatch on 2 arguments versus one, so no need for new name
for xy in xys # iterate over tracks
    fit!(o, xy) # fit all the coordinates
end
```

**Comment by joshday** [comment]
That exists in https://github.com/joshday/AverageShiftedHistograms.jl, but it would be nice to have it built into OnlineStats

**Comment by yakir12** [comment]
I guess a time will come when people will want to (on-line) fit **n**-dimensional histograms to their data... So it might be good to implement it in a generic enough way so to handle that as well. I have no idea what I'm talking about: maybe that is theoretically impossible.

**Comment by joshday** [comment]
I think `StatsBase.Histogram` can do N-dimensional fitting.  If I remember correctly, there's also a low level function that does online updating.

Also, apparently I forgot about [`OnlineStats.HeatMap`](https://joshday.github.io/OnlineStats.jl/latest/api/#OnlineStats.HeatMap) which does exactly what you want.

I think I like keeping `HeatMap` separate from `Hist` in order to keep the code cleaner (less type parameters, etc.)
