### ISSUE TITLE
Generalized regularization?

### ISSUE THREAD

**Issue by tbreloff** [joshday/OnlineStats.jl#21]
I'd like to be able to arbitrarily define a regularization function beyond the standard L1/L2.  For example it would be great to incorporate the change in beta: {lambda * (beta_t+1 - beta_t)} in the minimization, and not simply rely on the fixed speed of variation such as defined in online flexible least squares.  Also, I'd like this without needing to implement a brand new specialized OnlineStat.  Ideally lots of these concepts could be a little more plug and play (match user-defined regularization function with user defined link function, for example)

I have hopes that generalized Adagrad as a Weighting may provide this sort of flexibility, so for now I'm leaving this here as a "what if", and we can revisit later.

**Comment by joshday** [comment]
I have the start of something similar implemented in `linearmodel/sparsereg.jl`.  I'd like for the `SparseReg` type to allow users to get coefficients using an arbitrary penalty.  It explicitly supports OLS and Ridge (L2), but you can throw in an arbitrary penalty using `coef_solver()`.  Each call to `update!` only updates the "sufficient statistics".  Then, coefficients from arbitrary regularization schemes can be calculated afterwards.

`coef_solver()` is currently commented out because the dependency on Convex was causing some issues in the Travis builds, but the idea is to let the user define the penalty function.

```julia
# Take a user-defined penalty (a function supported by Convex.jl) and 
# plug it into a Convex Solver
# 
# objective is to minimize: .5 * β' * cor(x) * β - cor(x, y) * β + J(β)
function coef_solver(o::SparseReg, λ::Float64, penalty::Function,
                     solver::AbstractMathProgSolver = Convex.get_default_solver())
    o.s = cor(o.c)
    β = Convex.Variable(size(o.c.A, 1) - 1)
    p = Convex.minimize(.5 * Convex.quad_form(β, o.s[1:end-1, 1:end-1]) - vec(o.s[end, 1:end-1])' * β + λ * penalty(β))
    Convex.solve!(p, solver)
    scaled_to_original(β.value, mean(o.c), std(o.c))
end
```

For example, you could do:
```julia
coef_solver(o, λ, j)
```
with
```julia
j(β) = vecnorm(β, 1)  # lasso
j(β) = sum_squares(β)  # ridge
j(β) = vecnorm(D * β, 1)  # generalized lasso
```
At least in theory...this is largely untested.

**Comment by tbreloff** [comment]
Cool I missed this :+1:  I'll take a look.

**Comment by joshday** [comment]
Just a note: `stochasticmodel/penalty.jl` has all the penalty types (currently NoPenalty, L1Penalty, L2Penalty, ElasticNetPenalty, and SCADPenalty).  I think adding types is pretty straightforward.  If you want to add a new one, adding the corresponding methods will make it immediately available to StochasticModel and SparseReg.

**Comment by joshday** [comment]
Closing this, since this conversation now belongs in JuliaML.
