### ISSUE TITLE
What are the differences between Lag and MovingWindow?

### ISSUE THREAD

**Issue by astadmistry** [joshday/OnlineStats.jl#215]
I would first like to thank Josh @joshday and Tom @tbreloff for this awesome and extremely performant package!

The following pieces of code, both show the same result (when @show is appended to the "fit!(Mean()" line in each block), however both the allocation and run time (with GC disabled) are vastly different.

My questions are:
Why is the performance different?
Am I using the OnlineStats functions in the correct way to compute the moving average?
What is the difference between Lag and MovingWindow?

```julia
v = Vector(1:1000000)
GC.enable(false)
@time begin
    rolling = Lag(Int, 3)
    for ele in v
        fit!(rolling, ele)
        fit!(Mean(),value(rolling))
    end
end
GC.enable(true)
```
```
0.191212 seconds (4.00 M allocations: 91.537 MiB)
```
```julia
v = Vector(1:1000000)
GC.enable(false)
@time begin
    mw = MovingWindow(Int, 3)
    for ele in v
        fit!(mw, ele)
        fit!(Mean(),value(mw))
    end
end
GC.enable(true)
```
```
0.569484 seconds (8.00 M allocations: 488.266 MiB)
```
Many thanks
Astad Mistry

**Comment by joshday** [comment]
> I would first like to thank Josh `@joshday` and Tom `@tbreloff` for this awesome and extremely performant package!

Thanks!

---

**What is the difference between Lag and MovingWindow?**

I think originally `MovingWindow` had a function in the struct so that `value(movingwindow)` would return the function evaluated on the values.

As it stands they do the same thing, just with different implementations.

**Why is the performance different?** 

Different implementations.  Also benchmarking in global scope can give questionable results.

**Am I using the OnlineStats functions in the correct way to compute the moving average?**

I would just repeatedly call `mean` on the values of a `MovingWindow`
