### ISSUE TITLE
Weight in CountMap

### ISSUE THREAD

**Issue by ValdarT** [joshday/OnlineStats.jl#98]
Hi

Currently the counting in OnlineStats ignores weight. Is there any plan to change that?

I assume the only way of supporting weights for counts would be to have an array that stores the history (so you know what count to subtract from when it goes over the lookback number). Then the memory usage of counting depends on the lookback and weight type, of course, which is not that nice, but I think it would still be good to have that option. The memory usage dynamic just needs to be stated clearly in docs.

What do you think? Or perhaps you can think of a cleverer way of solving that?

**Comment by ValdarT** [comment]
PS: My specific use case is the classic Bayesian Bandit (Thompson sampling) with binomial outcome (success/failure). I want to sample from the distribution of probability of success – Beta(n_success, n_failure) but as the counts increase the distributions obviously get too narrow so I would want to apply a weight on the counting. 

I imagine that the situation where one wants to work directly with counts and cares about the absolute values not just proportions is not that uncommon.

**Comment by joshday** [comment]
There are a few types in OnlineStats that ignore the weight (`CountMap`, `Hist`, etc.) since they keep track of counts.  I have an idea for incorporating the weight that I haven't implemented yet, but it's not too complicated.

Just to clarify, in your case the probability of success is changing over time and you'd like to throw an `ExponentialWeight` on it or similar?

**Comment by ValdarT** [comment]
> Just to clarify, in your case the probability of success is changing over time and you'd like to throw an ExponentialWeight on it or similar?

Exactly

**Comment by ValdarT** [comment]
Do you have some timeline in mind, perhaps? Then I can decide whether I’ll wait for it or try to have a go at it myself (I’m in a bit of a hurry). For the second case, it would be good to hear your ideas on the implementation, of course, as you already gave it some thought.

**Comment by joshday** [comment]
My guess is I would get to it next week, but could very well be sooner (or later).  Sorry, I wish I could give you a smaller window.  Weighting counts is a little tricky in OnlineStats since a "weight" here is different from a "weight" in StatsBase.  We're essentially trying to translate the OnlineStats definition into the StatsBase definition, but it should be possible with fixed-size memory.

Anyways, my idea is this:  OnlineStats that have counts should store both `counts::Vector{Int}` and `weights::Vector{Float64}` (that always sums to 1).  

Suppose we just updated `counts[i]` and now we want to update `weights[i]` given our weight `w`:

```julia 
weights .*= (1 - w)
weights[i] += w
```

I haven't completely worked through the math but *I think* this does what we want it to.  If you have your own ideas, feel free to implement them, but `CountMap` is too important to remove the fixed memory requirement (I've been using it with some huge data in JuliaDB).

**Comment by ValdarT** [comment]
Thank you! That timeline is specific enough.

I initially thought about a similar approach but dismissed it because it seemed to have an issue. But actually the issue was with my reasoning. : D

**Comment by ufli** [comment]
Hi!

have you by any chance started working on the weighting issue?
@ValdarT and I have a quite restricted timeline so need to have this functionality soon, preferably by next week. Just wondering whether we should start working on it by ourselves or not :)

**Comment by ufli** [comment]
Hi!

Any updates on this?

**Comment by joshday** [comment]
It's still on my to-do list!  My PhD defense is tomorrow, so any spare time this week went into preparing for that.  I can say fairly confidently I'll have it done next week.

**Comment by Evizero** [comment]
Best of luck, Josh! (though to be on the safe side, do make sure that your defense won't rely on luck alone :) )

**Comment by ufli** [comment]
Oh! Good luck with your defense then :)

**Comment by ValdarT** [comment]
Good luck, indeed! Although judging based on OnlineStats, you won't need any - this is fantastic work you've done; I'm sure the dissertation isn't any different! : )

**Comment by joshday** [comment]
@ValdarT @ufli 

On master, I've changed the representation of CountMap to incorporate weights.  

- `value` still returns the same thing (Dict of label=>unweighted count).
- `keys` and `values` return the keys and values of the `value` Dict
- Weighted probabilities are available through `probs(o)`
- To get weighted counts, you would do `probs(o) .* values(o)`

I don't know if I'm completely satisfied with this interface, but I want to avoid converting Int64s to Float64s when you're using `EqualWeight`.

```
help?> CountMap
search: CountMap

  CountMap(T)

  Maintain a dictionary mapping unique values to its number of occurrences. Equivalent to StatsBase.countmap.

     Methods
    ≡≡≡≡≡≡≡≡≡

    •    value(o): Dict of raw counts

    •    keys(o): unique labels

    •    values(o): (unweighted) counts

    •    probs(o): weighted probabilities


     Example
    ≡≡≡≡≡≡≡≡≡

  vals = ["small", "medium", "large"]
  o = CountMap(String)
  s = Series(rand(vals, 1000), o)
  value(o)
  probs(o)
  probs(o, ["small", "large"])
```

**Comment by joshday** [comment]
Also FYI I passed my defense 🎉

**Comment by ufli** [comment]
Hi! Actually, in order to apply the weighting correctly one should do: probs(o) .*  sum(o.counts), instead of probs(o) .* values(o)
To me it seems like it would be more consistent to have values(o) already return weighted counts (in case user wants initial counts he can use EqualWeighting). Returning Floats would be weird indeed but why not just Int(round(x)) ?

**Comment by joshday** [comment]
Oh yep you're right, or `probs(o) .* nobs(o)`.

I could make `values(o)` return `Int.(round.(probs(o) .* nobs(o)))`, but that's not quite correct.  I'll think about this some more.

**Comment by ufli** [comment]
Hi!
We figured out that the first output that comes in to the Series (in categorical case) gets the initial weight 1 and the others have 0 by default.And then it messes up with the weighting scheme in Exponential case, since the category of the first one dominates over the others. It seems that it would be logical to assign initial weights to λ for all the categories before starting the fitting process. Does it make sense to you?

**Comment by ufli** [comment]
Hi!
We figured out that the first output that comes in to the Series (in categorical case) gets the initial weight 1 and the others have 0 by default.And then it messes up with the weighting scheme in Exponential case, since the category of the first one dominates over the others. It seems that it would be logical to assign initial weights to λ for all the categories before starting the fitting process. Does it make sense to you?

**Comment by ufli** [comment]
Hi!
We figured out that the first output that comes into the Series (in categorical case) gets the initial weight 1 and the others have 0 by default. Which messes up with the weighting scheme in Exponential case, since the category of the first one dominates over the others.

This example would illustrate the problem:

1. Initialize Series s with CountMap(String) [we created our wrapper around CountMap so it is possible to feed into Series) and ExponentialWeight() with default λ = 0.1
2. fit!(count_map_wrap, 0) and fit!(count_map_wrap, 1) [so in our case we have two possible outputs)
2. fit!(s, 0)
weights are:
0 and 1 for success and failure respectively
3. fit!(s, 1)
weights are:
0.1 and 0.9 respectively
4. fit!(s, 1)
weights are:
0.19 and 0.81 respectively
and so on

So even though the latest observations were successes, still the first failure dominates over them.
The period for this domination to go away depends on λ, but in general it seems that this bias introduced by the first fit! is crucial.

Wouldn't it be logical to assign initial weights to λ for all the categories before starting the fitting process? Even though we may be not aware of some categories at the beginning, the corresponding weight can be easily calculated once we get the new category outcome.

What do you think about this issue in general?

**Comment by joshday** [comment]
In general, I think `ExponentialWeight`'s current behavior is correct.  The `Weight` types require the first weight is going to be 1.  In your case, the first case will dominate only for a small number of updates and will quickly shrink to having less influence.

However, you can abuse this assumption by passing any function to produce weights.  I think something like this does what you want it to:

```
Series(rand(0:1, 100), x -> .1, CountMap(Int))
```

**Comment by ufli** [comment]
> In your case, the first case will dominate only for a small number of updates and will quickly shrink to having less influence
It highly depends on the λ value and on definition of quickly :)

So another illustrative example:

`s = OnlineStats.Series(ExponentialWeight(0.01), FitCategoricalTarget(1))`
▦ `Series{0}`
│ `ExponentialWeight(λ = 0.01) | nobs=0`
└── `FitCategoricalTarget{Int64}(CountMap{String}(Dict("failure"=>1,"success"=>1)))`

`fit!(s, 0)`
▦ `Series{0}`
│ `ExponentialWeight(λ = 0.01) | nobs=1`
└── `FitCategoricalTarget{Int64}(CountMap{String}(Dict("failure"=>2,"success"=>1)))`

`for i in 1:50
           fit!(s, 1)
 end`

` values(s.stats[1].counts)`
`2-element Array{Int64,1}:
51
2`

`OnlineStats.probs(s.stats[1].counts)`
`2-element Array{Float64,1}:
0.394994
0.605006`

**Comment by ufli** [comment]
> In your case, the first case will dominate only for a small number of updates and will quickly shrink to having less influence

It highly depends on the λ value and on definition of quickly :)

So another illustrative example:

`o = CountMap(Int)`
`CountMap{Int64}(Dict{Int64,Int64}())`

`s = Series([0], ExponentialWeight(0.01), o)`
▦ `Series{0}`
│ `ExponentialWeight(λ = 0.01) | nobs=1`
└── `CountMap{Int64}(Dict(0=>1))`

`for i in 1:50 fit!(s, 1) end`

`values(o)`
`2-element Array{Int64,1}:
 1
 50`

`probs(o)`
`2-element Array{Float64,1}:
 0.605006
 0.394994`

**Comment by joshday** [comment]
> It highly depends on the λ value and on definition of quickly :)

That's fair, but your example shows how `ExponentialWeight` is supposed to work. 

<img width="598" alt="screen shot 2018-02-02 at 10 18 56 am" src="https://user-images.githubusercontent.com/8075494/35740350-8578f19e-0802-11e8-925b-7e3193f7f133.png">

If you want to work around the first-weight-is-1 assumption, you can pass your own function.

**Comment by ValdarT** [comment]
I’m really not getting this. As per documentation on ExponentialWeight: “Each observation is weighted with a constant, giving newer observations higher influence and behaves similar to a rolling window.” 
In this case the initial observation overrides everything for a while and only after that the above statement becomes true. I can’t understand how this is desirable – the weight behaves counter to what is claimed for the first n observations.

**Comment by joshday** [comment]
Consider the update to a `Mean` (top of the page [here](http://joshday.github.io/OnlineStats.jl/latest/weights.html)).  Here is the difference between giving the first weight 1 vs. λ.

```julia
julia> s = Series(ExponentialWeight(.1), Mean()); fit!(s, 1000)
▦ Series{0}
│ ExponentialWeight(λ = 0.1) | nobs=1
└── Mean(1000.0)

julia> s = Series(x -> .1, Mean()); fit!(s, 1000)
▦ Series{0}
│ #9 | nobs=1
└── Mean(100.0)
```

If I use λ rather than 1, I get nonsense results for my `Mean` until I've seen a sufficient number of observations (opposite problem for `CountMap`).  

So while `ExponentialWeight` gives somewhat strange results for `CountMap`, it gives the expected result for the vast majority of other stats.  I also don't immediately see a way to special-case `CountMap`.  

I'll change the `ExponentialWeight` docs to make it more clear what's going on.

**Comment by joshday** [comment]
One more thing.  I think `McclainWeight` may also work for you.  It's like an `EqualWeight` that blends into `ExponentialWeight`.

**Comment by joshday** [comment]
On master, I just reverted `CountMap` back to its previous implementation to fix slowdowns for many categories (ref https://github.com/joshday/OnlineStats.jl/issues/108).

I renamed the newer implementation to `WeightedCountMap`.  I'm not quite satisfied with it, so I'm reopening the issue.

**Comment by joshday** [comment]
On master, there is now `ProbMap`, which tracks probabilities rather than counts and is capable of incorporating weights.  

```julia
julia> y = vcat(ones(100), 2ones(100));

julia> Series(y, ProbMap(Float64))
▦ Series{0}
│ EqualWeight | nobs=200
└── ProbMap: Dict(2.0=>0.5,1.0=>0.5)

julia> Series(y, x -> .01, ProbMap(Float64))
▦ Series{0}
│ #27 | nobs=200
└── ProbMap: Dict(2.0=>0.633968,1.0=>0.232053)
```
